### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by swevenstudio** [travellerse/qq-chatgpt#1]
null

**Comment by travellerse** [comment]
你好，我完成这个项目时使用的配置是，监听5700端口，使用9000端口反向http，建议如下配置gocq的配置文件
```
servers:
  - http: # HTTP 通信设置
      address: 0.0.0.0:5700 # HTTP监听地址
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:           # 反向HTTP POST地址列表
        - url: 'http://127.0.0.1:9000/' # 地址
          secret: ''                  # 密钥
          max-retries: 0             # 最大重试，0 时禁用
          retries-interval: 1000      # 重试时间，单位毫秒，0 时立即
```
